### PR TITLE
add support for eu433

### PR DESCRIPTION
**Pull request by tykling**
with love from Denmark

### CODE REVIEW

**Comment by brentru** [comment]
@tykling ThingsNetwork's website doesn't list the EU443 frequency plan:
https://www.thethingsnetwork.org/docs/lorawan/frequency-plans/#eu433

Is there a page which shows the frequency plan definition for this region?

**Comment by tykling** [comment]
Hello,

EU433 is not supported by TTN, but is a supported LoRa band in EU (hence the name). I use it in a private lorawan network in DK.

All devices must support the first three channels in the PR, 433.175, 433.375 and 433.575 MHz [1] [2]. The EU433 band is from 433.05 to 434.79 MHz. IIUC the gateway can dicate in a NewChannelReq which additional channels to use apart from the first three, inside that spectrum.

The RAK7249 gateway I have use the frequencies I put in the PR (the first three being the mandatory ones, and the rest are spaced evenly with 0.2 MHz like the first three). If higher data rate is desired channels could be spaced further apart, as needed, IIUC. 

This seemed like a sensible default - I guess it is easy to override if someone has an EU433 gateway with wider channels running :)

Best regards,

Thomas Steen Rasmussen

[1] https://www.everythingrf.com/community/lora-frequency-in-europe
[2] https://lora-alliance.org/wp-content/uploads/2020/11/lorawan_regional_parameters_v1.0.3reva_0.pdf

**Comment by tykling** [comment]
That was a long-winded way of saying: no sorry, I don't have a link to a frequency plan as such, because it is dynamic (apart from the first three). :)

**Comment by brentru** [comment]
> EU433 is not supported by TTN, but is a supported LoRa band in EU (hence the name). I use it in a private lorawan network in DK.

@tykling  Ok, this library is for TTN LoRaWAN network. 

Thank you for the contribution and the explanation - you are free to fork this repository and modify it to add EU433 support, but I do not want to support unofficial freq. plans.

**Pull request closed without merging**
